---
- hosts: localhost
  become: yes
  become_user: aur_builder
  tasks:
    # Install package_name using the first known helper found
    - name: Install packages from aur
      aur:
        skip_installed: yes
        name:
          - visual-studio-code-bin
          - vazir-fonts
          - postman-bin
          - behdad-fonts
          - emacs
