- hosts: localhost
  become: false
  tasks:
  - name: Neovim Config
    git: 
        repo: https://github.com/miladz68/vim-config.git 
        dest: $HOME/.config/nvim
        update: no

  - name: install pyton3 provider to neovim
    command: python3 -m pip install --user --upgrade pynvim

  - name: install pyton2 provider to neovim
    command: python2 -m pip install --user --upgrade pynvim

  - name: Install Plugins 
    command: nvim +PlugInstall +qall

  - name: Replace neovim editor 
    lineinfile:
        path: /home/milad/.profile
        regexp: 'export EDITOR=/usr/bin/nano'
        line: export EDITOR=/usr/bin/nvim

  - name: Alias vim to nvim
    lineinfile:
        path: /home/milad/.profile
        line: alias vim=nvim

  - name: Clone oh-my-zsh
    git: 
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
        update: no

  - name: create oh-my-zsh template
    command: cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

  - name: copy powerlevel.rc 
    command: cp ./powerlevel1.rc ~/.powerlevel.rc

  - name: source .profile in zshrc
    lineinfile:
        path: ~/.zshrc
        line: source ~/.profile
        
  - name: source .powerlevel in zshrc
    lineinfile:
        path: ~/.zshrc
        line: source ~/.powerlevel.rc

  - name: Clone powerlevel10k
    git: 
        repo: https://github.com/romkatv/powerlevel10k.git 
        dest: ~/.oh-my-zsh/themes/powerlevel10k
        update: no

  - name: set zsh theme to powerlevel10k 
    lineinfile:
        path: ~/.zshrc
        regex: 'ZSH_THEME=.*'
        line: ZSH_THEME=powerlevel10k/powerlevel10k

  - name: Change tilda font to GoMono 
    lineinfile:
        path: ~/.config/tilda/config_0
        regex: 'font=.*'
        line: font="GoMono Nerd Font 14"
  - name: set git user name
    git_config:
        name: user.name
        value: milad
        scope: global
  - name: set git email
    git_config:
        name: user.email
        value: mza1989@gmail.com
        scope: global

  - name: Install AUR ansible module
    git:
      repo: https://github.com/kewlfft/ansible-aur.git 
      dest: ~/.ansible/plugins/modules/aur
  # Install package_name using the first known helper found
  - name: Install packages from aur 
    aur: 
      skip_installed: yes
      name:
        - visual-studio-code-bin
        - vazir-fonts

  - name: setup yakuake
    lineinfile:
      dest: ~/.config/yakuakerc
      line: "{{ item.line }}"
    with_items:
      - { line: '[Window]' }
      - { line: 'Height=100' }
      - { line: 'Position=100' }
      - { line: 'Width=50' }
  - name: create scripts directory 
    file: path=~/scripts/ state=directory
  - name: Copy vs code shortcut script
    copy: 
      src: ./shortcut.sh
      dest: ~/scripts/shortcut.sh

  - name: create vs code shortcut in globalshortcutsrc
    command: kwriteconfig5 --file ~/.config/kglobalshortcutsrc --group khotkeys --key={5971d014-f454-481a-9a29-22f43dc0cb16} F9,none,Vscode

  - name: create vs code shortcut
    blockinfile:
      path: ~/.config/khotkeysrc
      block: |

        [Data_5]
        Comment=Lauch vscode
        Enabled=true
        Name=Vscode
        Type=SIMPLE_ACTION_DATA
        
        [Data_5Actions]
        ActionsCount=1
        
        [Data_5Actions0]
        CommandURL=sh /home/milad/scripts/shortcut.sh
        Type=COMMAND_URL
        
        [Data_5Conditions]
        Comment=
        ConditionsCount=0
        
        [Data_5Triggers]
        Comment=Simple_action
        TriggersCount=1
        
        [Data_5Triggers0]
        Key=F9
        Type=SHORTCUT
        Uuid={5971d014-f454-481a-9a29-22f43dc0cb16}


  - name: setup shortcut count to 5
    ini_file:
      path: ~/.config/khotkeysrc
      section: Data
      option: DataCount
      value: "5"

  - name: reset shortcut service
    command: qdbus org.kde.keyboard /modules/khotkeys org.kde.khotkeys.reread_configuration 
