- hosts: localhost
  become: true
  tasks:
  - name: Install Packages
    pacman: 
        name: [neovim, zsh, unzip, xclip, python2-pip, yay, chromium]

  - name: Alias vim to nvim for root user
    lineinfile:
        path: ~/.bashrc
        line: alias vim=nvim

  - name: create AUR builder user
    user:
      name: aur_builder
      group: wheel
      system: yes
  - name: add aur_builder to sudoers 
    lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      validate: 'visudo -cf %s'

  - name: Install oh-my-zsh
    command: sh -c sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended 
  - name: change shell to zsh
    user: 
        name: milad
        shell: /usr/bin/zsh 
  - name: download and install InconsolataGo nerdfont 
    get_url:
      url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/InconsolataGo/Regular/complete/InconsolataGo%20Nerd%20Font%20Complete%20Mono.ttf 
      dest: /usr/local/share/fonts/i/
  - name: download and install GoMono nerdfont 
    get_url:
      url: https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/Go-Mono/Regular/complete/Go%20Mono%20Nerd%20Font%20Complete.ttf
      dest: /usr/local/share/fonts/i/

  - name: stop newtork manger from overwriting dns servers
    copy:
      content: |
             [main]
             dns=none
      dest: /etc/NetworkManager/conf.d/99-dont-touch-my-dns.conf

  - name: setup shecan dns address
    lineinfile:
      dest: /etc/resolv.conf
      insertafter: '^#'
      line: "{{item}}"
    with_items:
      - nameserver 185.51.200.2
      - nameserver 178.22.122.100

- name: Install Aur packages
  import_playbook: aur.yml
- name: Install/Update Golang
  import_playbook: update-go.yml
        
